name: Run tests on Release

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017
        options: >-
          --health-cmd="mongosh --eval 'db.adminCommand(\"ping\")'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create .env file from secret
        run: echo "${{ secrets.webcur_env }}" > .env

      - name: Wait for MongoDB
        run: |
          for i in {1..10}; do
            nc -z localhost 27017 && break
            sleep 2
          done

      - name: Run tests
        run: pytest
